"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const BaseDao_1 = require("./BaseDao");
const Module_1 = require("../model/Module");
const tableName = "module";
const nameField = "module_name";
const typeField = "module_type";
const idField = "module_id";
class ModuleDao extends BaseDao_1.BaseDao {
    constructor(sqlConnector) {
        super(tableName, idField, sqlConnector);
    }
    getMapDataFromModel(model) {
        let result = new Map();
        result.set(this.idFieldName, model.id); // only needed for user; others id are autogenerated
        result.set(nameField, model.name);
        result.set(typeField, model.type);
        return result;
    }
    getModelFromRow(row) {
        return new Module_1.Module(row[idField], row[nameField], row[typeField]);
    }
}
exports.ModuleDao = ModuleDao;
//# sourceMappingURL=ModuleDao.js.map