"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const User_1 = require("../model/User");
const BaseDao_1 = require("./BaseDao");
const userDbTable = 'user';
const userNameField = 'user_name';
const userCorpoField = 'user_corpo';
const userIdField = 'user_id';
class UserDao extends BaseDao_1.BaseDao {
    constructor(sqlConnector) {
        super(userDbTable, userIdField, sqlConnector);
    }
    getMapDataFromModel(model) {
        let result = new Map();
        result.set(this.idFieldName, model.id); // only needed for user; others id are autogenerated
        result.set(userNameField, model.name);
        result.set(userCorpoField, model.corpo);
        return result;
    }
    getModelFromRow(row) {
        return new User_1.User(row[userIdField], row[userNameField], row[userCorpoField]);
    }
}
exports.UserDao = UserDao;
//# sourceMappingURL=UserDao.js.map