import {BaseDao} from "./BaseDao";
import {Ws} from "../model/Ws";
import {Sqlite} from "../../sql/Sqlite";

const tableName: string = "ws";

const dateField: string = "ws_date";
const statusField: string = "ws_status";

const idField: string = tableName + "_id"; 


export class WsDao extends BaseDao<Ws> {
    constructor(sqlConnector: Sqlite) {
        super(tableName, idField, sqlConnector);
    }

    protected getMapDataFromModel(model: Ws): Map<string, any> {
        let result: Map<string, any> = new Map<string, any>();
        //result.set(this.idFieldName, model.id); // only needed for user; others id are autogenerated
        result.set(dateField, model.startDate);
        result.set(statusField, model.status);
        return result;
    }

    protected getModelFromRow(row: any): Ws {
        return new Ws(row[idField], row[dateField], row[statusField]);
    }
}